language: rust
matrix:
  include:
  - env:
    - TARGET=x86_64-unknown-linux-gnu
    - ARCH=x86_64
  - env:
    - TARGET=x86_64-apple-darwin
    - ARCH=x86_64
    os: osx
rust:
  - nightly

before_cache:
  - chmod -R a+r $HOME/.cargo

cache: cargo

before_deploy:
- cargo build --release
- ls
- ls target
- ls target/release
- cd target/release
- tar -cvzf swerve.$TARGET.tar.gz swerve

deploy:
  - provider: releases
    api_key:
      secure: hoonHcAMie7yiZDkQdDzNYGU5zI2U8xCF70lZyvDMwwvicCn9vHCAxVDDGza6amFranfwQ8vKin3I6PYpNazt1VDrv+98dvkawFeJy30b0DNqo2uKaLN2IWA9IYjBTAVd2cSqA8vRhf89gfwA1x0/8pbosZXI7lF76kbU7QxiNfRVnc8uTOL2WBF7MjtqOKrQ+yQ7RQ/Bf+N31h6YR+HLknKZ+DZrZONKHVd62ThGcDajPYYOzODZlgrNct3asrO6QW5cYbIuguljXhPaWHpJ9130GDOOS3E7PQBBkxPJEI8+urZQ7aRQD7iu/DbDX3hkWPEh0BBUtJ8zlzv6T1dhwMkaqDsjGIv3Z/EdVt71DH+wocqF3wsiKfwGnmINu0atRlWCRT5nOhUb2UfWVoLYcHJOlU+nHkU4VRoPOlJaPwd3Ll98TBjObFl2khipKrKVcNc6zaaQQSVLrXZsaSHIDF8nTNgco4JP7V85FnS65hjXIzeiUP3SqAFMwmeGkRitCChIbYPgBfM46f+I3D4kJDy3Q1Yld3tLvDb+G4GuqsUYr9MFmXxInTN+ScruSW/eqeO3Cf2U0bcNBzSqGmCpSYFNwDNax+WhPnlNwNZwM6T0Co5i9BYUTdfnzzrFpuuCU36G20yD+lkAAvovfK5+yHWR1T4Qj72ij9/GacFKhw=
    skip_cleanup: true
    file: target/release/swerve.$TARGET.tar.gz
    on:
      repo: Commander-lol/rust-swerve
      tags: true
  - provider: s3
    secret_access_key:
      secure: McmrccPXOMutbRVqToC2fjRMNk2cACnuOae80uvOoUN/saj2BE88kSC4+MQbKk0+JlqyGcCc4hNbVyl3vPyAHwSnYNKCJhVL2fWiOKpoSJhzUaUAHTi1yC+19nY1Uzc3upb8ZD0uLc9ywYeOj/9rKx16ZpEk8toQF85KfuLLQWY46KTT3ILnG5+afHv9KOWThwYv4l7BoIsFIWzaFmNMEFF4LzLJFuoWrCkxr6FCeCD430nLVG5f8GihBP3ypy8VrFMz0vZz7sH4WX9C2RI/HFkgiTsl+DcIRdNDyx+KeyQCEIs7u+Tunm1oUmxGRcmoPBtSwG249ivqWEVWps6sYu0qahHmkmFi23t1+IhOwBLWhqBYQDr9EvtgscLZFmSaMCdLb0c5BUSsF6Pnblrsy25HbDr2BUZn7jq3dirvmek/PpLXaoY9HZ+8ozbepgvveI4qJGh5tXEBAnDKFY4Nbojpvmgw8swdw4XQTR4MFMCNMKJCmQ4xTk/Cj6VRnixMvwBqzKHFhbB65yvlDywzxCVKUsJL7qx28TWtHrDjI1HLMg/F4mFcB3lG6LHNBxaQSKkK5fR6PanseAr8/6WN/Vs1kfm7VW8xlbsAuLK13jz49L1IwI/RcJfehcUnBcP5H16Z44l3IdqtthUv00kd0F3F12Psov+6XYLieqFOmps=
    access_key_id:
      secure: B8PtE+QloD9AMF1xE2A81JSxMx6MkuIB4zSZ+uBUX1z0XAM3vpnPay/nONcm+K5RsdGy9e4FcmtYGgylRQYvWdbPn1Wfm3w3UGf608ZEYmIy5RkbQX0NgdTVT0rtM177CRjiVq3wjB9AB3n4h7RnFk9BZrNKAu/OQCA8NSnCcsZouXqFXqLVP7yfRNa8cKjiykv8BggFNUzltXxMaQ48l5kbwMVaErRdLrOFnCzQBxSyE9zdvnuQkErKxfmMZpVCkolHZXG2V62R84i5115obmR1ukPyfX8TQw6+uddtEWOA2oOM9o2c+XzDEv/5TXncqINLPGYBYaecvESn3vBvI84qF3fYTkJHlbDEjeu3Nk3BEEWoJ2ar7gbqeNHYpzvZsjGU/KQq/99op6wWh5vTkUX5WtQ+gqWIGoFJnaxS558XOz6wowH6vSRGXP4wsYdC2ycL1De73r+80vV9VuYKCxnv75HCYIDp/xal2USzPZH7fEL3MSq192dxko7yq8Yzg/EIqBDFQJTSIG+BNBewV+cYMzHnkzjHqJjBP7y8iYnNYl/0IpTKiDEg9OyJ+Kzvr1xjy5i8TiWGw+8nE9et6wBIeisYlws2NmsOlIKjqtY4nW5GYRqvgZvqVWkeN2Pp00xespJgwi9VCl0jpbMv1CXneIpoe0yhzM1+mvsZ59g=
    skip_cleanup: true
    bucket: swerve-server
    acl: public_read
    file: target/release/swerve.$TARGET.tar.gz
    on:
      repo: Commander-lol/rust-swerve
      tags: true
      branches:
        only:
          - master
