version: 2

jobs:
  build:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: abronan/rust-circleci:latest

  steps:
    - checkout
    - run: rustup nightly cargo build
    - save_cache:
        key: cargo-cache
        paths:
          - "~/.cargo"